apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-service
  name: my-service-1
spec:
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: service
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-service
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080

